--
-- Created by IntelliJ IDEA.
-- User: no0n3
-- Date: 01.12.17
-- Time: 14:38
-- To change this template use File | Settings | File Templates.
--


--card attributes
CARD_ATTRIBUTE_LIGHT = 500
CARD_ATTRIBUTE_DARK = 501
CARD_ATTRIBUTE_WATER = 502
CARD_ATTRIBUTE_WIND = 503
CARD_ATTRIBUTE_FIRE = 504
CARD_ATTRIBUTE_EARTH = 505
CARD_ATTRIBUTE_TRAP = 506
CARD_ATTRIBUTE_SPELL = 507

--card monster types
CARD_MONSTER_NORMAL = 401
CARD_MONSTER_EFFECT = 402
CARD_MONSTER_FUSION = 403
CARD_MONSTER_RITUAL = 404

CARD_MONSTER_TYPE_DRAGON = 510
CARD_MONSTER_TYPE_ZOMBIE = 511
CARD_MONSTER_TYPE_FIEND = 512
CARD_MONSTER_TYPE_PYRO = 513
CARD_MONSTER_TYPE_SEASERPENT = 514
CARD_MONSTER_TYPE_ROCK = 515
CARD_MONSTER_TYPE_MACHINE = 516
CARD_MONSTER_TYPE_FISH = 517
CARD_MONSTER_TYPE_DINOSAUR = 518
CARD_MONSTER_TYPE_INSECT = 519
CARD_MONSTER_TYPE_BEAST = 520
CARD_MONSTER_TYPE_BEASTWARRIOR = 521
CARD_MONSTER_TYPE_PLANT = 522
CARD_MONSTER_TYPE_AQUA = 523
CARD_MONSTER_TYPE_WARRIOR = 524
CARD_MONSTER_TYPE_WINGEDBEAST = 525
CARD_MONSTER_TYPE_FAIRY = 526
CARD_MONSTER_TYPE_SPELLCASTER = 527
CARD_MONSTER_TYPE_THUNDER = 528
CARD_MONSTER_TYPE_REPTILE = 529
CARD_MONSTER_TYPE_PSYCHIC = 530


--card spell types
CARD_SPELL_NORMAL = 405
CARD_SPELL_FIELD = 406
CARD_SPELL_CONTI = 407
CARD_SPELL_QUICK = 408
CARD_SPELL_RITUAL = 409
CARD_SPELL_EQUIP = 410


--card trap types
CARD_TRAP_NORMAL = 411
CARD_TRAP_CONTI = 412
CARD_TRAP_COUNTER = 413


--effect types
CARD_EFFECT_TYPE_DISCARD = 600
CARD_EFFECT_TYPE_DESTROY = 601
CARD_EFFECT_TYPE_DRAWCARD = 602
CARD_EFFECT_TYPE_TRIBUTE = 603
CARD_EFFECT_TYPE_LP_INCREASE = 604
CARD_EFFECT_TYPE_LP_DECREASE = 605
CARD_EFFECT_TYPE_DAMAGELP = 606
CARD_EFFECT_TYPE_ATK_INCREASE = 607
CARD_EFFECT_TYPE_ATK_DECREASE = 608
CARD_EFFECT_TYPE_DEF_INCREASE = 609
CARD_EFFECT_TYPE_DEF_DECREASE = 610
CARD_EFFECT_TYPE_DECK_GRAVEYARD_ENEMY = 611
CARD_EFFECT_TYPE_DECK_OGRAVEYARD = 612
CARD_EFFECT_TYPE_GRAVEYARD_HAND = 613
CARD_EFFECT_TYPE_GRAVEYARD_DECK = 614
CARD_EFFECT_TYPE_GRAVEYARD_FIELD = 615
CARD_EFFECT_TYPE_BANISH = 616
CARD_EFFECT_TYPE_SPIRIT = 617
CARD_EFFECT_TYPE_GEMINI = 618
CARD_EFFECT_TYPE_TOON = 619
CARD_EFFECT_TYPE_UNION = 620
CARD_EFFECT_TYPE_RITUAL = 621
CARD_EFFECT_TYPE_COIN = 622